name: nice
description: A thin wrapper over the dart team's http package.
version: 0.1.0
author: AnEnigmaticBug <anenigmaticbug@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
